// Generated by AI
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import { DashboardPage } from './DashboardPage';
import type { IndoorBuildingData } from '../../models/map';

const logoutMock = vi.fn();
const createMock = vi.fn();
const updateMock = vi.fn();
const removeMock = vi.fn();
const reloadMock = vi.fn();

const useMapsControllerMock = vi.fn();

vi.mock('../../controllers/auth/useAuthController', () => ({
  useAuthController: () => ({
    user: { username: 'alice', is_admin: false },
    token: 'token-123',
    logout: logoutMock,
  }),
}));

vi.mock('../../controllers/maps/useMapsController', () => ({
  useMapsController: (...args: unknown[]) => useMapsControllerMock(...args),
}));

function makeMap(overrides: Partial<IndoorBuildingData> = {}): IndoorBuildingData {
  return {
    id: 'map-1',
    name: 'Ground Floor',
    coords: { latitude: 51.5, longitude: -0.13 },
    floors: 1,
    rooms: 0,
    baseMap: { type: 'FeatureCollection', features: [] },
    NavGraph: { type: 'FeatureCollection', features: [] },
    BeaconPositions: { type: 'FeatureCollection', features: [] },
    ...overrides,
  };
}

function setupWithMaps(maps: IndoorBuildingData[]) {
  useMapsControllerMock.mockReturnValue({
    maps,
    loading: false,
    error: null,
    reload: reloadMock,
    create: createMock,
    update: updateMock,
    remove: removeMock,
  });

  render(<DashboardPage />);
}

describe('DashboardPage flows', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('creates a map from the New map flow', async () => {
    createMock.mockResolvedValue(undefined);
    setupWithMaps([]);

    fireEvent.click(screen.getByRole('button', { name: /new map/i }));

    fireEvent.change(screen.getByLabelText(/map name/i), { target: { value: 'Main Atrium' } });
    fireEvent.change(screen.getByLabelText(/latitude/i), { target: { value: '51.51' } });
    fireEvent.change(screen.getByLabelText(/longitude/i), { target: { value: '-0.14' } });

    fireEvent.click(screen.getByRole('button', { name: /^create$/i }));

    await waitFor(() => {
      expect(createMock).toHaveBeenCalledTimes(1);
      expect(createMock).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'Main Atrium',
          coords: { latitude: 51.51, longitude: -0.14 },
          floors: 1,
        }),
      );
    });
  });

  it('edits an existing map from the table edit action', async () => {
    updateMock.mockResolvedValue(undefined);
    setupWithMaps([makeMap()]);

    const row = screen.getByRole('row', { name: /ground floor/i });
    const buttons = within(row).getAllByRole('button');
    fireEvent.click(buttons[0]);

    fireEvent.change(screen.getByLabelText(/map name/i), { target: { value: 'Ground Floor Updated' } });
    fireEvent.click(screen.getByRole('button', { name: /save changes/i }));

    await waitFor(() => {
      expect(updateMock).toHaveBeenCalledTimes(1);
      expect(updateMock).toHaveBeenCalledWith(
        'map-1',
        expect.objectContaining({
          name: 'Ground Floor Updated',
          coords: { latitude: 51.5, longitude: -0.13 },
        }),
      );
    });
  });

  it('deletes a map through the delete confirmation dialog', async () => {
    removeMock.mockResolvedValue(undefined);
    setupWithMaps([makeMap()]);

    const row = screen.getByRole('row', { name: /ground floor/i });
    const buttons = within(row).getAllByRole('button');
    fireEvent.click(buttons[1]);

    fireEvent.click(screen.getByRole('button', { name: /^delete$/i }));

    await waitFor(() => {
      expect(removeMock).toHaveBeenCalledTimes(1);
      expect(removeMock).toHaveBeenCalledWith('map-1');
    });
  });
});
