// Generated by AI
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';

import { RegisterPage } from './RegisterPage';

const registerMock = vi.fn();
const navigateMock = vi.fn();

vi.mock('../../controllers/auth/useAuthController', () => ({
  useAuthController: () => ({
    register: registerMock,
  }),
}));

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual<typeof import('react-router-dom')>('react-router-dom');
  return {
    ...actual,
    useNavigate: () => navigateMock,
  };
});

function renderPage() {
  render(
    <MemoryRouter>
      <RegisterPage />
    </MemoryRouter>,
  );
}

describe('RegisterPage', () => {
  beforeEach(() => {
    registerMock.mockReset();
    navigateMock.mockReset();
  });

  it('shows form validation when fields are empty', async () => {
    renderPage();

    fireEvent.click(screen.getByRole('button', { name: /create account/i }));

    expect(await screen.findByText(/please fill in the form/i)).toBeInTheDocument();
    expect(registerMock).not.toHaveBeenCalled();
  });

  it('shows username conflict error for 409 responses', async () => {
    registerMock.mockRejectedValue({ response: { status: 409 } });
    renderPage();

    fireEvent.change(screen.getByLabelText(/username/i), { target: { value: 'alice' } });
    fireEvent.change(screen.getByLabelText(/password/i), { target: { value: 'good-pass' } });
    fireEvent.click(screen.getByRole('button', { name: /create account/i }));

    expect(await screen.findByText(/that username is already in use/i)).toBeInTheDocument();
  });

  it('navigates to login after successful registration', async () => {
    registerMock.mockResolvedValue(undefined);
    renderPage();

    fireEvent.change(screen.getByLabelText(/username/i), { target: { value: 'alice' } });
    fireEvent.change(screen.getByLabelText(/password/i), { target: { value: 'good-pass' } });
    fireEvent.click(screen.getByRole('button', { name: /create account/i }));

    await waitFor(() => {
      expect(registerMock).toHaveBeenCalledWith({ username: 'alice', password: 'good-pass' });
      expect(navigateMock).toHaveBeenCalledWith('/login', { replace: true });
    });
  });
});
