# Generated by AI

from fastapi.testclient import TestClient

import app.app as map_module
import app.routers.map as map_router
from app.app import app
from app.models.schemas import AuthenticatedUser

client = TestClient(app)


def setup_function():
    map_module._BUILDINGS.clear()


async def _fake_verify_token(_: str):
    return AuthenticatedUser(username="tester", is_admin=True)


async def _fake_verify_token_by_token(token: str):
    if token == "alice-token":
        return AuthenticatedUser(username="alice", is_admin=False)
    if token == "bob-token":
        return AuthenticatedUser(username="bob", is_admin=False)
    if token == "admin-token":
        return AuthenticatedUser(username="admin", is_admin=True)
    return AuthenticatedUser(username="unknown", is_admin=False)


def _headers(token: str = "test-token"):
    return {"Authorization": f"Bearer {token}"}


def _payload(name: str = "Main Hall"):
    return {
        "name": name,
        "coords": {"latitude": 51.5, "longitude": -0.13},
        "floors": 2,
        "baseMap": {
            "type": "FeatureCollection",
            "features": [
                {"type": "Feature", "properties": {"feature_type": "hallway"}},
                {"type": "Feature", "properties": {"feature_type": "unit"}},
                {"type": "Feature", "properties": {"feature_type": "UNIT"}},
            ],
        },
        "NavGraph": {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {"type": "LineString", "coordinates": [[0, 0], [1, 1]]},
                    "properties": {"from_id": "A", "to_id": "B", "cost": 1},
                }
            ],
        },
        "BeaconPositions": {
            "type": "FeatureCollection",
            "features": [{"type": "Feature"}, {"type": "Feature"}],
        },
    }


def test_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"Service_Name": "MapAPI", "Author": "Thomas Sargent"}


def test_create_update_delete_requires_authentication():
    unauth_list = client.get("/buildings")
    assert unauth_list.status_code == 401


    unauth_create = client.post("/buildings", json=_payload())
    assert unauth_create.status_code == 401

    map_router.verify_token_with_auth_api = _fake_verify_token

    created = client.post("/buildings", json=_payload(), headers=_headers())
    assert created.status_code == 201
    assert created.json()["author"] == "tester"
    building_id = created.json()["id"]

    updated = client.put(
        f"/buildings/{building_id}",
        json=_payload("Updated Hall"),
        headers=_headers(),
    )
    assert updated.status_code == 200
    assert updated.json()["name"] == "Updated Hall"

    deleted = client.delete(f"/buildings/{building_id}", headers=_headers())
    assert deleted.status_code == 204


def test_list_returns_building_summary_shape():
    map_router.verify_token_with_auth_api = _fake_verify_token

    created = client.post("/buildings", json=_payload(), headers=_headers())
    assert created.status_code == 201

    listed = client.get("/buildings", headers=_headers())
    assert listed.status_code == 200
    body = listed.json()
    assert len(body) == 1
    assert body[0]["name"] == "Main Hall"
    assert body[0]["floors"] == 2
    assert body[0]["rooms"] == 2
    assert body[0]["author"] == "tester"


def test_non_owner_cannot_access_or_modify_building():
    map_router.verify_token_with_auth_api = _fake_verify_token_by_token

    created = client.post("/buildings", json=_payload(), headers=_headers("alice-token"))
    assert created.status_code == 201
    building_id = created.json()["id"]

    list_for_owner = client.get("/buildings", headers=_headers("alice-token"))
    assert list_for_owner.status_code == 200
    assert len(list_for_owner.json()) == 1

    list_for_non_owner = client.get("/buildings", headers=_headers("bob-token"))
    assert list_for_non_owner.status_code == 200
    assert len(list_for_non_owner.json()) == 0

    get_for_non_owner = client.get(f"/buildings/{building_id}")
    assert get_for_non_owner.status_code == 200

    update_for_non_owner = client.put(
        f"/buildings/{building_id}",
        json=_payload("Updated by Bob"),
        headers=_headers("bob-token"),
    )
    assert update_for_non_owner.status_code == 403

    delete_for_non_owner = client.delete(f"/buildings/{building_id}", headers=_headers("bob-token"))
    assert delete_for_non_owner.status_code == 403

    delete_for_admin = client.delete(f"/buildings/{building_id}", headers=_headers("admin-token"))
    assert delete_for_admin.status_code == 204


def test_admin_can_list_all_buildings_across_users():
    map_router.verify_token_with_auth_api = _fake_verify_token_by_token

    created_alice = client.post("/buildings", json=_payload("Alice Hall"), headers=_headers("alice-token"))
    assert created_alice.status_code == 201

    created_bob = client.post("/buildings", json=_payload("Bob Hall"), headers=_headers("bob-token"))
    assert created_bob.status_code == 201

    non_admin_all = client.get("/buildings/all")
    assert non_admin_all.status_code == 200

    admin_all = client.get("/buildings/all")
    assert admin_all.status_code == 200
    body = admin_all.json()
    assert len(body) == 2
    authors = {item["author"] for item in body}
    names = {item["name"] for item in body}
    assert authors == {"alice", "bob"}
    assert names == {"Alice Hall", "Bob Hall"}
