// Generated by AI

import { fetchAllBuildings, fetchIndoorBuildingData, getPresenceBeaconsByBuilding } from '../api/buildings';
import apiClient from '../api/client';
import type { IndoorBuildingData } from '../api/types';

jest.mock('../api/client', () => ({
  __esModule: true,
  default: {
    get: jest.fn(),
  },
}));

const mockedApiClient = apiClient as jest.Mocked<typeof apiClient>;

describe('api/buildings', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('fetchAllBuildings maps nullable author values', async () => {
    mockedApiClient.get.mockResolvedValueOnce({
      data: [
        {
          id: '1',
          name: 'Main',
          coords: { latitude: 1, longitude: 2 },
          floors: 3,
          rooms: 10,
          author: undefined,
        },
      ],
    } as never);

    const result = await fetchAllBuildings();

    expect(mockedApiClient.get).toHaveBeenCalledWith('/buildings/all');
    expect(result).toEqual([
      {
        id: '1',
        name: 'Main',
        coords: { latitude: 1, longitude: 2 },
        floors: 3,
        rooms: 10,
        author: null,
      },
    ]);
  });

  it('fetchIndoorBuildingData maps API model to app model', async () => {
    mockedApiClient.get.mockResolvedValueOnce({
      data: {
        id: 'b-1',
        name: 'HQ',
        coords: { latitude: 51.5, longitude: -0.1 },
        floors: 4,
        baseMap: { type: 'FeatureCollection', features: [] },
        NavGraph: { type: 'FeatureCollection', features: [] },
        BeaconPositions: { type: 'FeatureCollection', features: [] },
        author: null,
      },
    } as never);

    const result = await fetchIndoorBuildingData('b-1');

    expect(mockedApiClient.get).toHaveBeenCalledWith('/buildings/b-1');
    expect(result.geojson).toEqual({ type: 'FeatureCollection', features: [] });
    expect(result.NavGraph).toEqual({ type: 'FeatureCollection', features: [] });
    expect(result.BeaconPositions).toEqual({ type: 'FeatureCollection', features: [] });
    expect(result.floors).toBe(4);
  });

  it('getPresenceBeaconsByBuilding maps only point features', () => {
    const indoor: IndoorBuildingData = {
      id: 'b',
      name: 'B',
      coords: { latitude: 0, longitude: 0 },
      floors: 2,
      geojson: { type: 'FeatureCollection', features: [] },
      NavGraph: { type: 'FeatureCollection', features: [] },
      BeaconPositions: {
        type: 'FeatureCollection',
        features: [
          {
            type: 'Feature',
            properties: { mac_address: 'aa:bb', room_id: 'Room 1' },
            geometry: { type: 'Point', coordinates: [1, 2] },
          },
          {
            type: 'Feature',
            properties: { mac_address: 'cc:dd', room_id: 'Room 2' },
            geometry: { type: 'LineString', coordinates: [[0, 0], [1, 1]] },
          },
        ],
      },
      author: null,
    };

    const result = getPresenceBeaconsByBuilding(indoor);

    expect(result).toEqual([
      {
        id: 'aa:bb',
        name: 'Room 1',
        coords: { longitude: 1, latitude: 2 },
      },
    ]);
  });
});
