// Generated by AI

import { formatRoomNameForUi } from '../utils/formatRoomName';

describe('formatRoomNameForUi', () => {
  it('returns empty string for nullish input', () => {
    expect(formatRoomNameForUi(undefined)).toBe('');
    expect(formatRoomNameForUi(null)).toBe('');
    expect(formatRoomNameForUi('')).toBe('');
  });

  it('formats underscore-separated room names into title case', () => {
    expect(formatRoomNameForUi('north_wing_101')).toBe('North Wing 101');
  });

  it('normalizes mixed case and extra separators', () => {
    expect(formatRoomNameForUi('mAIn__LOBBY')).toBe('Main Lobby');
  });
});
