// Generated by AI

jest.mock('@turf/turf', () => ({
  centroid: (feature: { geometry: { coordinates: number[][][] } }) => {
    const ring = feature.geometry.coordinates[0];
    const unique = ring.slice(0, ring.length - 1);
    const count = unique.length || 1;
    const sum = unique.reduce(
      (acc, [x, y]) => ({ x: acc.x + x, y: acc.y + y }),
      { x: 0, y: 0 }
    );
    return {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [sum.x / count, sum.y / count],
      },
      properties: {},
    };
  },
}));

import type { FeatureCollection, Geometry } from 'geojson';

import { checkArrival, getRoomCenters, normalizeRoomKey } from '../utils/mapUtils';

describe('mapUtils', () => {
  describe('normalizeRoomKey', () => {
    it('strips non-alphanumeric characters and lowercases', () => {
      expect(normalizeRoomKey('Room_1-A')).toBe('room1a');
    });
  });

  describe('checkArrival', () => {
    it('returns false when either room is missing', () => {
      expect(checkArrival(null, { name: 'A', level: 0 })).toBe(false);
      expect(checkArrival({ name: 'A', level: 0 }, null)).toBe(false);
    });

    it('matches destination by normalized room name', () => {
      expect(
        checkArrival(
          { name: 'Room_101', level: 1 },
          { name: 'room 101', level: 1 }
        )
      ).toBe(true);
    });
  });

  describe('getRoomCenters', () => {
    it('returns centers for unit features only', () => {
      const geojson: FeatureCollection<Geometry> = {
        type: 'FeatureCollection',
        features: [
          {
            type: 'Feature',
            properties: { feature_type: 'unit', name: 'ROOM_A', level_id: 2 },
            geometry: {
              type: 'Polygon',
              coordinates: [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]],
            },
          },
          {
            type: 'Feature',
            properties: { feature_type: 'corridor', name: 'HALL_1', level_id: 2 },
            geometry: {
              type: 'Polygon',
              coordinates: [[[2, 2], [2, 3], [3, 3], [3, 2], [2, 2]]],
            },
          },
        ],
      };

      const centers = getRoomCenters(geojson);

      expect(centers.size).toBe(1);
      expect(centers.has('ROOM_A')).toBe(true);
      expect(centers.get('ROOM_A')?.level).toBe(2);
    });
  });
});
