// Generated by AI

jest.mock('@turf/turf', () => ({
  lineString: (coordinates: [number, number][]) => ({
    type: 'Feature',
    geometry: { type: 'LineString', coordinates },
    properties: {},
  }),
  length: (line: { geometry: { coordinates: [number, number][] } }) => {
    const coords = line.geometry.coordinates;
    let total = 0;
    for (let i = 1; i < coords.length; i += 1) {
      const [x1, y1] = coords[i - 1];
      const [x2, y2] = coords[i];
      total += Math.hypot(x2 - x1, y2 - y1) * 1000;
    }
    return total;
  },
}));

import type { PathEdgesData } from '../types/map';
import { generatePath } from '../utils/pathfinding';

describe('generatePath', () => {
  const graph: PathEdgesData = {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: { from_id: 'a', to_id: 'b', cost: 1 },
        geometry: { type: 'LineString', coordinates: [[0, 0], [0, 1]] },
      },
      {
        type: 'Feature',
        properties: { from_id: 'b', to_id: 'c', cost: 1 },
        geometry: { type: 'LineString', coordinates: [[0, 1], [1, 1]] },
      },
    ],
  };

  it('returns null for invalid start/end', () => {
    expect(generatePath('', 'c', graph)).toBeNull();
    expect(generatePath('a', '', graph)).toBeNull();
    expect(generatePath('a', 'a', graph)).toBeNull();
  });

  it('returns shortest path with node ids and distance', () => {
    const result = generatePath('a', 'c', graph);

    expect(result).not.toBeNull();
    expect(result?.nodeIds).toEqual(['a', 'b', 'c']);
    expect(result?.geometry.geometry.type).toBe('LineString');
    expect(result?.distance).toBeGreaterThan(0);
  });

  it('throws when start/end nodes are not present in the graph', () => {
    const disconnected: PathEdgesData = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: { from_id: 'x', to_id: 'y', cost: 1 },
          geometry: { type: 'LineString', coordinates: [[10, 10], [11, 11]] },
        },
      ],
    };

    expect(() => generatePath('a', 'c', disconnected)).toThrow('fromId is not defined in this graph: a');
  });
});
