// Generated by AI

import { Colors, Fonts, Theme_Options } from '../constants/theme';

describe('theme constants', () => {
  it('defines all expected theme options', () => {
    expect(Theme_Options.map((item) => item.id)).toEqual(['system', 'light', 'dark']);
  });

  it('contains detected room color in both light and dark map palettes', () => {
    expect(Colors.light.map3d.detectedRoom).toBeTruthy();
    expect(Colors.dark.map3d.detectedRoom).toBeTruthy();
  });

  it('exposes font families', () => {
    expect(Fonts).toBeDefined();
    expect((Fonts as any).sans).toBeTruthy();
    expect((Fonts as any).mono).toBeTruthy();
  });
});
