// Generated by AI

jest.mock('@turf/turf', () => ({
  point: (coords: [number, number]) => ({ geometry: { coordinates: coords } }),
  bearing: (
    from: { geometry: { coordinates: [number, number] } },
    to: { geometry: { coordinates: [number, number] } }
  ) => {
    const [x1, y1] = from.geometry.coordinates;
    const [x2, y2] = to.geometry.coordinates;
    return (Math.atan2(y2 - y1, x2 - x1) * 180) / Math.PI;
  },
}));

import { buildTurnByTurnSteps } from '../utils/turnByTurn';

describe('buildTurnByTurnSteps', () => {
  it('returns empty when input is invalid', () => {
    expect(buildTurnByTurnSteps([], [])).toEqual([]);
    expect(buildTurnByTurnSteps(['a'], [[0, 0]])).toEqual([]);
    expect(buildTurnByTurnSteps(['a', 'b'], [[0, 0]])).toEqual([]);
  });

  it('builds steps across room transitions', () => {
    const nodeIds = ['room_a_a', 'room_a_b', 'room_b_a', 'room_c_a'];
    const coords: [number, number][] = [[0, 0], [0, 1], [1, 1], [2, 1]];

    const steps = buildTurnByTurnSteps(nodeIds, coords);

    expect(steps.length).toBeGreaterThan(0);
    expect(steps[0].fromRoomKey).toBe('room_a');
    expect(steps[0].toRoomKey).toBe('room_b');
    expect(steps[steps.length - 1].toRoomKey).toBe('room_c');
  });

  it('returns empty when all nodes are within the same room key', () => {
    const nodeIds = ['room_a_a', 'room_a_b'];
    const coords: [number, number][] = [[0, 0], [0, 1]];

    const steps = buildTurnByTurnSteps(nodeIds, coords);

    expect(steps).toEqual([]);
  });
});
