// Generated by AI

describe('useBuildings', () => {
  const flush = async () => {
    await Promise.resolve();
    await Promise.resolve();
  };

  it('loads buildings on mount and updates state on success', async () => {
    jest.resetModules();

    const mockSetBuildings = jest.fn();
    const mockSetLoading = jest.fn();
    const mockSetError = jest.fn();
    const mockFetchAllBuildings = jest.fn().mockResolvedValue([{ id: '1', name: 'Main' }]);

    jest.doMock('react', () => ({
      ...jest.requireActual('react'),
      useState: jest
        .fn()
        .mockImplementationOnce((initial: unknown) => [initial, mockSetBuildings])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoading])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetError]),
      useCallback: (fn: unknown) => fn,
      useEffect: (effect: () => void) => effect(),
    }));

    jest.doMock('@/api/buildings', () => ({
      fetchAllBuildings: mockFetchAllBuildings,
    }));

    const { useBuildings } = require('../hooks/map/buildings/useBuildings');
    const result = useBuildings();

    await flush();

    expect(mockFetchAllBuildings).toHaveBeenCalledTimes(1);
    expect(mockSetLoading).toHaveBeenCalledWith(true);
    expect(mockSetError).toHaveBeenCalledWith(null);
    expect(mockSetBuildings).toHaveBeenCalledWith([{ id: '1', name: 'Main' }]);
    expect(mockSetLoading).toHaveBeenCalledWith(false);
    expect(typeof result.refetch).toBe('function');
  });

  it('sets error when loading buildings fails', async () => {
    jest.resetModules();

    const mockSetBuildings = jest.fn();
    const mockSetLoading = jest.fn();
    const mockSetError = jest.fn();
    const mockFetchAllBuildings = jest.fn().mockRejectedValue(new Error('Network down'));

    jest.doMock('react', () => ({
      ...jest.requireActual('react'),
      useState: jest
        .fn()
        .mockImplementationOnce((initial: unknown) => [initial, mockSetBuildings])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoading])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetError]),
      useCallback: (fn: unknown) => fn,
      useEffect: (effect: () => void) => effect(),
    }));

    jest.doMock('@/api/buildings', () => ({
      fetchAllBuildings: mockFetchAllBuildings,
    }));

    const { useBuildings } = require('../hooks/map/buildings/useBuildings');
    useBuildings();

    await flush();

    expect(mockSetError).toHaveBeenCalledWith('Network down');
    expect(mockSetLoading).toHaveBeenCalledWith(false);
  });
});
