// Generated by AI

jest.mock('react', () => ({
  ...jest.requireActual('react'),
  useMemo: (factory: () => unknown) => factory(),
}));

jest.mock('../hooks/map/bluetooth/useLiveBleRssi', () => ({
  useLiveBleRssi: jest.fn(),
}));

import { useBeaconPresence } from '../hooks/map/bluetooth/useBeaconPresence';
import { useLiveBleRssi } from '../hooks/map/bluetooth/useLiveBleRssi';

const mockedUseLiveBleRssi = useLiveBleRssi as jest.MockedFunction<typeof useLiveBleRssi>;

describe('useBeaconPresence', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('returns UNKNOWN when disabled', () => {
    mockedUseLiveBleRssi.mockReturnValue({ readings: {}, isScanning: false, error: null });

    const result = useBeaconPresence({ enabled: false, beacons: [] });

    expect(result.room).toBe('UNKNOWN');
    expect(result.position).toBeNull();
    expect(result.statuses).toEqual([]);
  });

  it('picks nearest active beacon as current room', () => {
    mockedUseLiveBleRssi.mockReturnValue({
      readings: {
        aabb: { id: 'aabb', rssi: -50, isRunning: true },
        ccdd: { id: 'ccdd', rssi: -80, isRunning: true },
      },
      isScanning: true,
      error: null,
    });

    const beacons = [
      { id: 'aa:bb', name: 'room_1', coords: { latitude: 10, longitude: 20 } },
      { id: 'cc:dd', name: 'room_2', coords: { latitude: 30, longitude: 40 } },
    ];

    const result = useBeaconPresence({ enabled: true, beacons });

    expect(result.room).toBe('ROOM_1');
    expect(result.statuses).toHaveLength(2);
  });
});
