// Generated by AI

jest.mock('react', () => ({
  ...jest.requireActual('react'),
  useMemo: (factory: () => unknown) => factory(),
  useCallback: (fn: unknown) => fn,
  useState: (initial: unknown) => [initial, jest.fn()],
}));

jest.mock('react-native-reanimated', () => {
  const withTiming = jest.fn((value: number) => value);
  return {
    Easing: {
      exp: jest.fn(() => 'exp'),
      out: jest.fn((value: unknown) => value),
    },
    useSharedValue: (value: number) => ({ value }),
    withTiming,
    __mockWithTiming: withTiming,
  };
});

import * as Reanimated from 'react-native-reanimated';

import { BUTTON_HEIGHT } from '../components/ui/map/indoorMap/FloorPicker';
import { useFloorManagement } from '../hooks/map/indoorMap/useFloorManagement';

describe('useFloorManagement', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('builds floor levels from a numeric floor count', () => {
    const result = useFloorManagement(4);

    expect(result.mapFloors).toEqual([0, 1, 2, 3]);
    expect(result.activeLevel).toBe(0);
  });

  it('falls back to a single ground floor for invalid counts', () => {
    expect(useFloorManagement(0).mapFloors).toEqual([0]);
    expect(useFloorManagement(-2).mapFloors).toEqual([0]);
  });

  it('updates translateY when changing to a valid floor', () => {
    const result = useFloorManagement(3);
    const mockWithTiming = (Reanimated as any).__mockWithTiming as jest.Mock;

    result.handleLevelChange(2);

    expect(mockWithTiming).toHaveBeenCalledWith(0 * BUTTON_HEIGHT, expect.any(Object));
    expect(result.translateY.value).toBe(0);
  });

  it('ignores invalid floor changes', () => {
    const result = useFloorManagement(2);
    const mockWithTiming = (Reanimated as any).__mockWithTiming as jest.Mock;

    result.translateY.value = 123;
    result.handleLevelChange(10);

    expect(mockWithTiming).not.toHaveBeenCalled();
    expect(result.translateY.value).toBe(123);
  });
});
