// Generated by AI

describe('useIndoorBuildingData', () => {
  const flush = async () => {
    await Promise.resolve();
    await Promise.resolve();
  };

  it('loads indoor building data and marks state ready', async () => {
    jest.resetModules();

    const mockSetData = jest.fn();
    const mockSetLoadState = jest.fn();
    const mockSetLoadError = jest.fn();
    const mockSetReloadToken = jest.fn();

    const mockFetchIndoorBuildingData = jest.fn().mockResolvedValue({
      geojson: { type: 'FeatureCollection', features: [{ type: 'Feature' }] },
    });

    jest.doMock('react', () => ({
      ...jest.requireActual('react'),
      useState: jest
        .fn()
        .mockImplementationOnce((initial: unknown) => [initial, mockSetData])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoadState])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoadError])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetReloadToken]),
      useCallback: (fn: unknown) => fn,
      useMemo: (factory: () => unknown) => factory(),
      useEffect: (effect: () => void | (() => void)) => effect(),
    }));

    jest.doMock('@/api/buildings', () => ({
      fetchIndoorBuildingData: mockFetchIndoorBuildingData,
    }));

    const originalSetTimeout = global.setTimeout;
    const originalClearTimeout = global.clearTimeout;
    const mockClearTimeout = jest.fn();

    (global as any).setTimeout = (fn: () => void) => {
      fn();
      return 1;
    };
    (global as any).clearTimeout = mockClearTimeout;

    const { useIndoorBuildingData } = require('../hooks/map/buildings/useIndoorBuildingData');
    const result = useIndoorBuildingData('building-1');

    await flush();

    expect(mockFetchIndoorBuildingData).toHaveBeenCalledWith('building-1');
    expect(mockSetLoadState).toHaveBeenCalledWith('loading');
    expect(mockSetLoadError).toHaveBeenCalledWith(null);
    expect(mockSetData).toHaveBeenCalled();
    expect(mockSetLoadState).toHaveBeenCalledWith('ready');
    expect(typeof result.reload).toBe('function');

    (global as any).setTimeout = originalSetTimeout;
    (global as any).clearTimeout = originalClearTimeout;
  });

  it('sets error state when building id is missing', async () => {
    jest.resetModules();

    const mockSetData = jest.fn();
    const mockSetLoadState = jest.fn();
    const mockSetLoadError = jest.fn();
    const mockSetReloadToken = jest.fn();
    const mockFetchIndoorBuildingData = jest.fn();

    jest.doMock('react', () => ({
      ...jest.requireActual('react'),
      useState: jest
        .fn()
        .mockImplementationOnce((initial: unknown) => [initial, mockSetData])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoadState])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetLoadError])
        .mockImplementationOnce((initial: unknown) => [initial, mockSetReloadToken]),
      useCallback: (fn: unknown) => fn,
      useMemo: (factory: () => unknown) => factory(),
      useEffect: (effect: () => void | (() => void)) => effect(),
    }));

    jest.doMock('@/api/buildings', () => ({
      fetchIndoorBuildingData: mockFetchIndoorBuildingData,
    }));

    const originalSetTimeout = global.setTimeout;
    const originalClearTimeout = global.clearTimeout;

    (global as any).setTimeout = (fn: () => void) => {
      fn();
      return 1;
    };
    (global as any).clearTimeout = jest.fn();

    const { useIndoorBuildingData } = require('../hooks/map/buildings/useIndoorBuildingData');
    useIndoorBuildingData(undefined);

    await flush();

    expect(mockFetchIndoorBuildingData).not.toHaveBeenCalled();
    expect(mockSetLoadError).toHaveBeenCalledWith('No building id was provided.');
    expect(mockSetLoadState).toHaveBeenCalledWith('error');

    (global as any).setTimeout = originalSetTimeout;
    (global as any).clearTimeout = originalClearTimeout;
  });
});
