// Generated by AI

jest.mock('react', () => ({
  ...jest.requireActual('react'),
  useMemo: (factory: () => unknown) => factory(),
}));

jest.mock('@turf/turf', () => ({
  centroid: (feature: any) => ({
    type: 'Feature',
    geometry: { type: 'Point', coordinates: feature.geometry.coordinates[0][0] },
    properties: {},
  }),
  buffer: (poly: any) => ({ ...poly }),
  featureCollection: (features: any[]) => ({ type: 'FeatureCollection', features }),
  difference: () => ({
    type: 'Feature',
    geometry: {
      type: 'Polygon',
      coordinates: [[[0, 0], [0, 0.2], [0.2, 0.2], [0.2, 0], [0, 0]]],
    },
    properties: {},
  }),
}));

import type { FeatureCollection, Geometry } from 'geojson';
import { useIndoorData } from '../hooks/map/rendering/useIndoorData';

describe('useIndoorData', () => {
  it('filters by level and builds map, labels and detected room data', () => {
    const geojson: FeatureCollection<Geometry> = {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: { feature_type: 'unit', name: 'ROOM_A', level_id: 1 },
          geometry: {
            type: 'Polygon',
            coordinates: [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]],
          },
        },
        {
          type: 'Feature',
          properties: { feature_type: 'unit', name: 'ROOM_B', level_id: 2 },
          geometry: {
            type: 'Polygon',
            coordinates: [[[2, 2], [2, 3], [3, 3], [3, 2], [2, 2]]],
          },
        },
      ],
    };

    const result = useIndoorData(geojson, 1, 'room a');

    expect(result.mapData?.features.length).toBe(2);
    expect(result.labelData?.features.length).toBe(1);
    expect(result.detectedRoomData?.features.length).toBe(1);
    expect(result.detectedRoomData?.features[0].properties?.name).toBe('ROOM_A');
  });

  it('returns undefined datasets when no geojson is provided', () => {
    const result = useIndoorData(undefined, 0, null);

    expect(result.mapData).toBeUndefined();
    expect(result.labelData).toBeUndefined();
    expect(result.detectedRoomData).toBeUndefined();
  });
});
