// Generated by AI

jest.mock('react', () => ({
  ...jest.requireActual('react'),
  useMemo: (factory: () => unknown) => factory(),
}));

jest.mock('../hooks/map/bluetooth/useBeaconPresence', () => ({
  useBeaconPresence: jest.fn(),
}));

jest.mock('../api/buildings', () => ({
  getPresenceBeaconsByBuilding: jest.fn(),
}));

import { getPresenceBeaconsByBuilding } from '../api/buildings';
import type { IndoorBuildingData } from '../api/types';
import { useBeaconPresence } from '../hooks/map/bluetooth/useBeaconPresence';
import { useMapPresence } from '../hooks/map/indoorMap/useMapPresence';

const mockedUseBeaconPresence = useBeaconPresence as jest.MockedFunction<typeof useBeaconPresence>;
const mockedGetPresenceBeaconsByBuilding = getPresenceBeaconsByBuilding as jest.MockedFunction<typeof getPresenceBeaconsByBuilding>;

describe('useMapPresence', () => {
  const indoorBuildingData: IndoorBuildingData = {
    id: 'b1',
    name: 'Building',
    coords: { latitude: 0, longitude: 0 },
    floors: 2,
    geojson: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: { feature_type: 'unit', name: 'ROOM_101', level_id: 1 },
          geometry: {
            type: 'Polygon',
            coordinates: [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]],
          },
        },
      ],
    },
    NavGraph: { type: 'FeatureCollection', features: [] },
    BeaconPositions: { type: 'FeatureCollection', features: [] },
    author: null,
  };

  beforeEach(() => {
    jest.clearAllMocks();
    mockedGetPresenceBeaconsByBuilding.mockReturnValue([{ id: 'x', name: 'X', coords: { latitude: 0, longitude: 0 } }]);
  });

  it('maps detected room name to room selection', () => {
    mockedUseBeaconPresence.mockReturnValue({ room: 'room 101', position: null, statuses: [], isScanning: true, error: null });

    const result = useMapPresence(indoorBuildingData);

    expect(result.detectedRoom).toEqual({ name: 'ROOM_101', level: 1 });
    expect(result.autoLocation).toBe(true);
    expect(result.presenceError).toBeNull();
  });

  it('disables autoLocation when room is unknown', () => {
    mockedUseBeaconPresence.mockReturnValue({ room: 'UNKNOWN', position: null, statuses: [], isScanning: true, error: 'test' });

    const result = useMapPresence(indoorBuildingData);

    expect(result.detectedRoom).toBeNull();
    expect(result.autoLocation).toBe(false);
    expect(result.presenceError).toBe('test');
  });
});
