// Generated by AI

jest.mock('react', () => ({
  ...jest.requireActual('react'),
  useMemo: (factory: () => unknown) => factory(),
  useCallback: (fn: unknown) => fn,
}));

jest.mock('../utils/mapUtils', () => ({
  getRoomCenters: jest.fn(),
}));

import { useMapCamera } from '../hooks/map/indoorMap/useMapCamera';
import { getRoomCenters } from '../utils/mapUtils';

const mockedGetRoomCenters = getRoomCenters as jest.MockedFunction<typeof getRoomCenters>;

describe('useMapCamera', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('snaps camera to known room center and triggers level change', () => {
    const setCamera = jest.fn();
    const cameraRef = { current: { setCamera } } as any;

    mockedGetRoomCenters.mockReturnValue(
      new Map([
        ['ROOM_1', { longitude: 1.23, latitude: 4.56, level: 2 }],
      ])
    );

    const { snapToRoom } = useMapCamera(cameraRef, { geojson: { type: 'FeatureCollection', features: [] } } as any);
    const onLevelChange = jest.fn();

    snapToRoom('ROOM_1', onLevelChange);

    expect(onLevelChange).toHaveBeenCalledWith(2);
    expect(setCamera).toHaveBeenCalledWith({
      centerCoordinate: [1.23, 4.56],
      zoomLevel: 20,
      animationDuration: 700,
      animationMode: 'easeTo',
    });
  });

  it('does nothing when room center is unknown', () => {
    const setCamera = jest.fn();
    const cameraRef = { current: { setCamera } } as any;

    mockedGetRoomCenters.mockReturnValue(new Map());

    const { snapToRoom } = useMapCamera(cameraRef, { geojson: { type: 'FeatureCollection', features: [] } } as any);

    snapToRoom('MISSING');

    expect(setCamera).not.toHaveBeenCalled();
  });
});
