// Generated by AI

jest.mock('../hooks/theme/use-color-scheme', () => ({
  useColorScheme: jest.fn(),
}));

import { useColorScheme } from '../hooks/theme/use-color-scheme';
import { useThemeColor } from '../hooks/theme/use-theme-color';

const mockedUseColorScheme = useColorScheme as jest.MockedFunction<typeof useColorScheme>;

describe('useThemeColor', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('returns explicit themed prop when provided', () => {
    mockedUseColorScheme.mockReturnValue('dark');

    const color = useThemeColor({ dark: '#111111', light: '#eeeeee' }, 'text');

    expect(color).toBe('#111111');
  });

  it('falls back to theme palette when prop is missing', () => {
    mockedUseColorScheme.mockReturnValue('light');

    const color = useThemeColor({}, 'text');

    expect(color).toBe('#11181C');
  });

  it('defaults to light theme when hook returns null', () => {
    mockedUseColorScheme.mockReturnValue(null as never);

    const color = useThemeColor({}, 'background');

    expect(color).toBe('#fff');
  });
});
