// Generated by AI
import { describe, expect, it } from 'vitest';

import { authApi, mapApi } from './apiClient';

describe('apiClient', () => {
  it('configures auth and map axios clients with base URLs', () => {
    expect(authApi.defaults.baseURL).toContain('/auth');
    expect(mapApi.defaults.baseURL).toContain('/map');
  });
});
