# Generated by AI

from fastapi.testclient import TestClient


from app.app import app

client = TestClient(app)


def test_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"Service_Name": "AuthAPI", "Author": "Thomas Sargent"}


def test_register_login_verify_and_logout_flow():
    register = client.post("/register", json={"username": "alice", "password": "supersecret1"})
    assert register.status_code == 201
    assert register.json() == {"username": "alice", "is_admin": False}

    login = client.post("/login", json={"username": "alice", "password": "supersecret1"})
    assert login.status_code == 200
    token = login.json()["access_token"]

    verify = client.post("/verify-token", headers={"Authorization": f"Bearer {token}"})
    assert verify.status_code == 200
    assert verify.json() == {"username": "alice", "is_admin": False}

    logout = client.post("/logout", headers={"Authorization": f"Bearer {token}"})
    assert logout.status_code == 200

    verify_again = client.post("/verify-token", headers={"Authorization": f"Bearer {token}"})
    assert verify_again.status_code == 401
