# Generated by AI

from fastapi.testclient import TestClient

from app.app import app

client = TestClient(app)


def test_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"Service_Name": "LoggingAPI", "Author": "Thomas Sargent"}


def test_create_and_list_logs():
    created = client.post(
        "/logs",
        json={
            "service": "map_api",
            "level": "info",
            "message": "building.created",
            "method": "POST",
            "path": "/buildings",
            "status_code": 201,
        },
    )
    assert created.status_code == 201

    listed = client.get("/logs?service=map_api")
    assert listed.status_code == 200
    entries = listed.json()
    assert any(entry["message"] == "building.created" for entry in entries)


def test_request_middleware_adds_request_logs():
    client.get("/")
    listed = client.get("/logs")
    assert listed.status_code == 200
    entries = listed.json()
    assert any(entry.get("path") == "/" for entry in entries)
